# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Split - left is central
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Enable USB on central
CONFIG_ZMK_USB=y

# Enable BLE
CONFIG_ZMK_BLE=y

# Increase BT power for better range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable experimental BLE connection support
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Sleep configuration
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_ZMK_SLEEP=y

# Enable support to control external power output
CONFIG_ZMK_EXT_POWER=n

# Enable I2C and Azoteq TPS43 touchpad support
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_INPUT_TPS43=y

# Enable logging over USB serial
CONFIG_LOG=y
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOG_LEVEL_DBG=y

# I2C and input debug logging
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_INPUT_LOG_LEVEL_DBG=y
